security_register:
    path:    /register
    defaults: { _controller: RCHJWTUserBundle:Security:register }
    requirements:
        methods: POST

security_oauth_login:
    path:    /oauth/login
    defaults: { _controller: RCHJWTUserBundle:Security:loginFromOAuthResponse }
    requirements:
        methods: POST

security_refresh_token:
    path:     /refresh_token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    requirements:
        methods: POST
