services:
    rch_jwt_user.credential_fetcher:
        class: RCH\JWTUserBundle\Service\CredentialFetcher
        arguments:
            requestStack: @request_stack
            validator: @validator
            container: @service_container

    rch_jwt_user.jwt_response_listener:
        class: RCH\JWTUserBundle\EventListener\JwtResponseListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
